/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/chat-zh': RouteRecordInfo<'/chat-zh', '/chat-zh', Record<never, never>, Record<never, never>>,
    '/collective-sponsor-onetime': RouteRecordInfo<'/collective-sponsor-onetime', '/collective-sponsor-onetime', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/giving-talks': RouteRecordInfo<'/giving-talks', '/giving-talks', Record<never, never>, Record<never, never>>,
    '/media': RouteRecordInfo<'/media', '/media', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/photos': RouteRecordInfo<'/photos', '/photos', Record<never, never>, Record<never, never>>,
    '/podcasts': RouteRecordInfo<'/podcasts', '/podcasts', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/AI-dilemma': RouteRecordInfo<'/posts/AI-dilemma', '/posts/AI-dilemma', Record<never, never>, Record<never, never>>,
    '/posts/AI-helps': RouteRecordInfo<'/posts/AI-helps', '/posts/AI-helps', Record<never, never>, Record<never, never>>,
    '/posts/dog-my-cats': RouteRecordInfo<'/posts/dog-my-cats', '/posts/dog-my-cats', Record<never, never>, Record<never, never>>,
    '/posts/remote-repo-authentication': RouteRecordInfo<'/posts/remote-repo-authentication', '/posts/remote-repo-authentication', Record<never, never>, Record<never, never>>,
    '/posts/shift-from-responsibility': RouteRecordInfo<'/posts/shift-from-responsibility', '/posts/shift-from-responsibility', Record<never, never>, Record<never, never>>,
    '/posts/start-a-blog': RouteRecordInfo<'/posts/start-a-blog', '/posts/start-a-blog', Record<never, never>, Record<never, never>>,
    '/posts/weekly_review_01_250309': RouteRecordInfo<'/posts/weekly_review_01_250309', '/posts/weekly_review_01_250309', Record<never, never>, Record<never, never>>,
    '/posts/weekly_review_02_250316': RouteRecordInfo<'/posts/weekly_review_02_250316', '/posts/weekly_review_02_250316', Record<never, never>, Record<never, never>>,
    '/posts/weekly_review_03_250323': RouteRecordInfo<'/posts/weekly_review_03_250323', '/posts/weekly_review_03_250323', Record<never, never>, Record<never, never>>,
    '/posts/weekly_review_04_250330': RouteRecordInfo<'/posts/weekly_review_04_250330', '/posts/weekly_review_04_250330', Record<never, never>, Record<never, never>>,
    '/posts/weekly_review_05_250406': RouteRecordInfo<'/posts/weekly_review_05_250406', '/posts/weekly_review_05_250406', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/sponsors-list': RouteRecordInfo<'/sponsors-list', '/sponsors-list', Record<never, never>, Record<never, never>>,
    '/streams': RouteRecordInfo<'/streams', '/streams', Record<never, never>, Record<never, never>>,
    '/talks': RouteRecordInfo<'/talks', '/talks', Record<never, never>, Record<never, never>>,
  }
}
